# Generated by Django 3.2.16 on 2024-05-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_question_next_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Choice'), ('text', 'Text')], default='choice', max_length=10),
        ),
    ]
