# Generated by Django 3.2.16 on 2024-05-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20240519_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textresponse',
            options={'ordering': ('response',), 'verbose_name': 'Текстовый ответ', 'verbose_name_plural': 'Текстовые ответы'},
        ),
    ]
